// Fixed, curated Contributor Team list (CD2 — launch scope; the
// full dynamically-current official list is fast-follow). Each
// team carries the full CD3 field set: what the team does, who it
// suits, whether technical knowledge is required, a beginner-friendly
// task, and concretely what to do at that team's table.

export const CONTRIB_TEAMS = [
  {
    id: 'core',
    name: 'Core',
    emoji: '💻',
    technical: true,
    matches: ['code', 'development'],
    whoItSuits: 'Developers who enjoy fixing bugs or building features in WordPress itself.',
    description: 'Works on WordPress the software — the code that runs on millions of sites.',
    beginnerTask: 'Try reproducing a reported bug on a test site and confirm the steps in the ticket.',
    atTheTable: 'Say you\'re new to Core — ask for a "good first bug" to try.',
  },
  {
    id: 'test',
    name: 'Testing',
    emoji: '🧪',
    technical: false,
    matches: ['testing', 'code', 'curious'],
    whoItSuits: 'Detail-oriented people who like trying to break things on purpose — no coding required.',
    description: 'Tries out new features before release and reports what does and doesn\'t work.',
    beginnerTask: 'Follow a test scenario on the current beta and report your result.',
    atTheTable: 'Ask "what needs testing today?" — there\'s usually a live list.',
  },
  {
    id: 'docs',
    name: 'Documentation',
    emoji: '📚',
    technical: false,
    matches: ['writing', 'documentation', 'curious'],
    whoItSuits: 'Clear writers who like explaining things simply.',
    description: 'Writes and maintains the guides that help people actually use WordPress.',
    beginnerTask: 'Read one existing doc page and flag a sentence that\'s confusing to a beginner.',
    atTheTable: 'Ask which doc page gets the most confused feedback — that\'s where help is wanted.',
  },
  {
    id: 'support',
    name: 'Support',
    emoji: '💬',
    technical: false,
    matches: ['support', 'people', 'curious'],
    whoItSuits: 'Patient people who like helping someone solve a problem, one question at a time.',
    description: 'Answers real user questions on the WordPress.org support forums.',
    beginnerTask: 'Read an open forum thread and see if you can spot what\'s actually being asked.',
    atTheTable: 'Ask to shadow an answer being written — most Support contributors are happy to show the ropes.',
  },
  {
    id: 'polyglots',
    name: 'Polyglots',
    emoji: '🌍',
    technical: false,
    matches: ['translation', 'people', 'curious'],
    whoItSuits: 'Anyone fluent in a language other than English (technical background not required).',
    description: 'Translates WordPress so it\'s usable in languages beyond English.',
    beginnerTask: 'Translate a handful of short strings into a language you speak well.',
    atTheTable: 'Mention which language(s) you speak — that\'s literally the first question they\'ll ask.',
  },
  {
    id: 'design',
    name: 'Design',
    emoji: '✦',
    technical: false,
    matches: ['design', 'curious'],
    whoItSuits: 'People who think about how something looks and feels to use.',
    description: 'Shapes the interface and experience of the WordPress admin and editor.',
    beginnerTask: 'Look at a current design discussion and share what\'s unclear to you as a user.',
    atTheTable: 'Bring a specific screen you find confusing in WordPress — it\'s a great conversation starter.',
  },
  {
    id: 'training',
    name: 'Training',
    emoji: '🎓',
    technical: false,
    matches: ['organizing', 'people', 'writing'],
    whoItSuits: 'People who like teaching or building learning material.',
    description: 'Builds the lesson plans and workshops used to teach WordPress worldwide.',
    beginnerTask: 'Read one published lesson and suggest a clearer example.',
    atTheTable: 'Ask what topic most needs a fresh lesson written — there\'s usually a backlog.',
  },
  {
    id: 'community',
    name: 'Community',
    emoji: '🤝',
    technical: false,
    matches: ['organizing', 'people'],
    whoItSuits: 'Organizers who enjoy making events and spaces feel welcoming.',
    description: 'Runs the program behind meetups and WordCamps — the reason this event exists.',
    beginnerTask: 'Ask what it takes to help organize a local WordPress meetup.',
    atTheTable: 'Ask what the biggest challenge running THIS WordCamp was — you\'ll learn a lot fast.',
  },
  {
    id: 'accessibility',
    name: 'Accessibility',
    emoji: '♿',
    technical: false,
    matches: ['testing', 'design', 'curious'],
    whoItSuits: 'Anyone who cares that WordPress works for people using screen readers, keyboards, or other assistive tech.',
    description: 'Makes sure WordPress is usable by everyone, regardless of ability.',
    beginnerTask: 'Try navigating a WordPress admin screen using only your keyboard and note where you get stuck.',
    atTheTable: 'Ask for one concrete accessibility issue you could help verify.',
  },
  {
    id: 'photography',
    name: 'Photography',
    emoji: '📷',
    technical: false,
    matches: ['design', 'curious'],
    whoItSuits: 'Photographers, even casual ones, who enjoy shooting free-to-use images.',
    description: 'Contributes free photos to the WordPress Photo Directory that anyone can use on their site.',
    beginnerTask: 'Bring a few original photos on your phone and ask how to submit one.',
    atTheTable: 'Ask what kind of photos the directory is short on right now.',
  },
];

export const CONTRIB_QUESTION_TAGS = [
  { key: 'development', label: 'Writing code' },
  { key: 'testing', label: 'Testing things' },
  { key: 'writing', label: 'Writing' },
  { key: 'documentation', label: 'Explaining things clearly' },
  { key: 'design', label: 'Design' },
  { key: 'support', label: 'Helping people 1-on-1' },
  { key: 'translation', label: 'Translation' },
  { key: 'organizing', label: 'Organizing events' },
  { key: 'people', label: 'Meeting people' },
  { key: 'curious', label: "Not sure yet — I'm just curious" },
];
