// Fixed, curated Contributor Team list (CD2 — launch scope; the
// full dynamically-current official list is fast-follow). Each
// team carries the full CD3 field set: what the team does, who it
// suits, whether technical knowledge is required, a beginner-friendly
// task, and concretely what to do at that team's table.

export const CONTRIB_TEAMS = [
  {
    id: 'core',
    name: 'Core',
    icon: 'laptop',
    technical: true,
    matches: ['code', 'development'],
    whoItSuits: 'Developers who enjoy fixing bugs or building features in WordPress itself.',
    description: 'Works on the WordPress software itself, the code that runs on millions of sites.',
    beginnerTask: 'Try reproducing a reported bug on a test site and confirm the steps in the ticket.',
    atTheTable: 'Say you\'re new to Core and ask for a "good first bug" to try.',
  },
  {
    id: 'test',
    name: 'Testing',
    icon: 'flask',
    technical: false,
    matches: ['testing', 'code', 'curious'],
    whoItSuits: 'Careful people who enjoy breaking things on purpose. No coding needed.',
    description: 'Tries out new features before release and reports what does and doesn\'t work.',
    beginnerTask: 'Follow a test scenario on the current beta and report your result.',
    atTheTable: 'Ask "What needs testing today?" There\'s usually a list.',
  },
  {
    id: 'docs',
    name: 'Documentation',
    icon: 'book-open',
    technical: false,
    matches: ['writing', 'documentation', 'curious'],
    whoItSuits: 'Clear writers who like explaining things simply.',
    description: 'Writes and maintains the guides that help people actually use WordPress.',
    beginnerTask: 'Read one existing doc page and flag a sentence that\'s confusing to a beginner.',
    atTheTable: 'Ask which doc page confuses people the most. That\'s where they need help.',
  },
  {
    id: 'support',
    name: 'Support',
    icon: 'message-circle',
    technical: false,
    matches: ['support', 'people', 'curious'],
    whoItSuits: 'Patient people who like helping someone solve a problem, one question at a time.',
    description: 'Answers real user questions on the WordPress.org support forums.',
    beginnerTask: 'Read an open forum thread and see if you can spot what\'s actually being asked.',
    atTheTable: 'Ask to watch someone write an answer. Most Support people are happy to show you how.',
  },
  {
    id: 'polyglots',
    name: 'Polyglots',
    icon: 'globe',
    technical: false,
    matches: ['translation', 'people', 'curious'],
    whoItSuits: 'Anyone fluent in a language other than English (technical background not required).',
    description: 'Translates WordPress so it\'s usable in languages beyond English.',
    beginnerTask: 'Translate a handful of short strings into a language you speak well.',
    atTheTable: 'Say which languages you speak. It\'s the first thing they\'ll ask.',
  },
  {
    id: 'design',
    name: 'Design',
    icon: 'pen-tool',
    technical: false,
    matches: ['design', 'curious'],
    whoItSuits: 'People who think about how something looks and feels to use.',
    description: 'Shapes the interface and experience of the WordPress admin and editor.',
    beginnerTask: 'Look at a current design discussion and share what\'s unclear to you as a user.',
    atTheTable: 'Bring one WordPress screen you find confusing. It\'s an easy way to start talking.',
  },
  {
    id: 'training',
    name: 'Training',
    icon: 'graduation-cap',
    technical: false,
    matches: ['organizing', 'people', 'writing'],
    whoItSuits: 'People who like teaching or building learning material.',
    description: 'Builds the lesson plans and workshops used to teach WordPress worldwide.',
    beginnerTask: 'Read one published lesson and suggest a clearer example.',
    atTheTable: 'Ask which topic most needs a new lesson. There\'s usually a list waiting.',
  },
  {
    id: 'community',
    name: 'Community',
    icon: 'users',
    technical: false,
    matches: ['organizing', 'people'],
    whoItSuits: 'Organizers who enjoy making events and spaces feel welcoming.',
    description: 'Runs the program behind meetups and WordCamps, including this one.',
    beginnerTask: 'Ask what it takes to help organize a local WordPress meetup.',
    atTheTable: 'Ask what was hardest about running this WordCamp. You\'ll learn a lot in five minutes.',
  },
  {
    id: 'accessibility',
    name: 'Accessibility',
    icon: 'accessibility',
    technical: false,
    matches: ['testing', 'design', 'curious'],
    whoItSuits: 'Anyone who cares that WordPress works for people using screen readers, keyboards, or other assistive tech.',
    description: 'Makes sure WordPress is usable by everyone, regardless of ability.',
    beginnerTask: 'Try navigating a WordPress admin screen using only your keyboard and note where you get stuck.',
    atTheTable: 'Ask for one concrete accessibility issue you could help verify.',
  },
  {
    id: 'photography',
    name: 'Photography',
    icon: 'camera',
    technical: false,
    matches: ['design', 'curious'],
    whoItSuits: 'Photographers, even casual ones, who enjoy shooting free-to-use images.',
    description: 'Contributes free photos to the WordPress Photo Directory that anyone can use on their site.',
    beginnerTask: 'Bring a few original photos on your phone and ask how to submit one.',
    atTheTable: 'Ask what kind of photos the directory is short on right now.',
  },
];

export const CONTRIB_QUESTION_TAGS = [
  { key: 'development', label: 'Writing code' },
  { key: 'testing', label: 'Testing things' },
  { key: 'writing', label: 'Writing' },
  { key: 'documentation', label: 'Explaining things clearly' },
  { key: 'design', label: 'Design' },
  { key: 'support', label: 'Helping people 1-on-1' },
  { key: 'translation', label: 'Translation' },
  { key: 'organizing', label: 'Organizing events' },
  { key: 'people', label: 'Meeting people' },
  { key: 'curious', label: "Not sure yet, just curious" },
];
