@extends('errors.layout')
@section('title', 'Page not found')
@section('code', 'Error 404')
@section('art', 'lost')
@section('heading', "We couldn't find that page")
@section('message', "The link may be old, or this WordCamp isn't live in CampBuddy yet. Pick your event from the list and you'll be right back on track.")
