@extends('errors.layout')
@section('title', 'Slow down')
@section('code', 'Too many requests')
@section('art', 'wait')
@section('heading', 'Too many taps at once')
@section('message', 'At a conference lots of people share one wifi connection, so we slow things down a little. Wait a minute and try again.')
