
// NOTE: several fields below (name, tagline, starts, conference, venue,
// address, hashtag, officialUrl, ticketUrl, directionsUrl, contactUrl,
// ticketPrice, socials) are refreshed in place by
// scripts/build-wcr-assets.py from the live /events API on every run —
// hand-edits to those specific fields will be overwritten next run. The
// rest of this object (id, shortName, timezone, scheduleUrl,
// contributorUrl, sponsorsUrl, codeOfConductUrl, facts) has no live
// equivalent and is safe to hand-edit permanently.
const EVENT = {
  id: "rajasthan-2026",
  name: "WordCamp Rajasthan 2026",
  shortName: "Rajasthan 2026",
  tagline: "The first unified state-level WordCamp for Rajasthan.",
  starts: "2026-10-03T09:00:00+05:30",
  conference: "2026-10-04T09:00:00+05:30",
  timezone: "Asia/Kolkata",
  venue: "Rajasthan Internation Center",
  address: "Jaipur, Rajasthan, 302015",
  hashtag: "#wcrajasthan",
  officialUrl: "https://rajasthan.wordcamp.org/2026/",
  scheduleUrl: "https://rajasthan.wordcamp.org/2026/schedule/",
  contributorUrl: "https://rajasthan.wordcamp.org/2026/contribute-learn-connect/",
  contactUrl: "mailto:rajasthan@wordcamp.org",
  ticketUrl: "https://rajasthan.wordcamp.org/2026/tickets/",
  ticketPrice: "₹1,000 for both days",
  sponsorsUrl: "https://rajasthan.wordcamp.org/2026/sponsors/",
  codeOfConductUrl: "https://rajasthan.wordcamp.org/2026/code-of-conduct/",
  directionsUrl: "https://maps.app.goo.gl/gY6LQXWuZqM7kam86",
  socials: [
    ["Instagram","https://www.instagram.com/wprajasthan"],
    ["Facebook","https://www.facebook.com/wprajasthan"],
    ["X","https://x.com/wprajasthan"],
    ["LinkedIn","https://www.linkedin.com/company/wprajasthan"]
  ],
  facts: [
    "Contributor Day · 3 October",
    "Conference Day · 4 October",
    "2 parallel tracks",
    "20 talks & workshops"
  ]
};

// Fallback, used until (or unless) the live event API below returns real
// sponsor data (with logos). Kept in the same {tier,cls,items} shape as the
// live-derived version — items are {name,url,logo:null}. Regenerated by
// scripts/build-wcr-assets.py from the live /events sponsor list — don't
// hand-edit the block below; edits are overwritten on next run.
// AUTO-GENERATED:SPONSORS_FALLBACK START
const SPONSORS_FALLBACK = [
  {tier:"Platinum", cls:"platinum", items:[
    {name:"Elicus", url:"https://elicus.com", logo:"https://rajasthan.wordcamp.org/2026/files/2026/09/elicus-logo.webp"},
    {name:"Hostinger", url:"http://hostinger.com/", logo:"https://rajasthan.wordcamp.org/2026/files/2026/07/Hostinger-logo-primary-1.png"},
    {name:"Yoast", url:"", logo:"https://rajasthan.wordcamp.org/2026/files/2026/07/yoast_logo_rgb.png"},
    {name:"Woo", url:"https://woo.com/", logo:"https://rajasthan.wordcamp.org/2026/files/2026/01/Woo-Logo-New.png"},
    {name:"WordPress.com", url:"https://automattic.com/about/", logo:"https://rajasthan.wordcamp.org/2026/files/2026/01/wordpressdotcom_lockup-black-scaled.png"}
  ]},
  {tier:"Silver", cls:"silver", items:[
    {name:"Elementor", url:"https://elementor.com", logo:"https://rajasthan.wordcamp.org/2026/files/2026/08/Elementor-Pink-400x70-1.png.webp"},
    {name:"WPVibes", url:"", logo:"https://rajasthan.wordcamp.org/2026/files/2026/08/wpv-logo.png"},
    {name:"AddWeb Solution", url:"https://www.addwebsolution.com", logo:"https://rajasthan.wordcamp.org/2026/files/2026/08/add-web-horizontal-logo-dark-CMYK-scaled.png"}
  ]},
  {tier:"Bronze", cls:"bronze", items:[
    {name:"Uichemy", url:"https://uichemy.com/", logo:"https://rajasthan.wordcamp.org/2026/files/2026/09/Logo-UiChemy.png"},
    {name:"SEOPress", url:"https://www.seopress.org", logo:"https://rajasthan.wordcamp.org/2026/files/2026/09/SEOPress-logo.png"},
    {name:"WPBakery", url:"https://wpbakery.com", logo:"https://rajasthan.wordcamp.org/2026/files/2026/09/wpb-logo.png"},
    {name:"SynthCoder", url:"https://synthcoder.com", logo:"https://rajasthan.wordcamp.org/2026/files/2026/08/Logo-Synth.png"}
  ]}
];
// AUTO-GENERATED:SPONSORS_FALLBACK END

const EXPLORE_CHANNEL_URL = "https://www.youtube.com/@wpsimplifiedbysunil";
// Fallback list, used until (or unless) the live API below returns usable
// data. Regenerated by scripts/build-wcr-assets.py from the live /media
// list — don't hand-edit the block below; edits are overwritten on next run.
// AUTO-GENERATED:EXPLORE_VIDEOS_FALLBACK START
const EXPLORE_VIDEOS_FALLBACK = [
  {id:"WKtSb8kJCy8",title:"WordCamp Rajasthan 2026 Kya Hai? Jaipur Mein Event",type:"short"},
  {id:"UmrucSBxSiU",title:"WordCamp Rajasthan 2026 Kya Hai? Jaipur Event Guide",type:"short"},
  {id:"WT3gUmLxcm0",title:"WordCamp Rajasthan 2026 Kya Hai? Jaipur Mein",type:"short"},
  {id:"L74vcp4KEYU",title:"Elementor Developer Nirbhay Singh Rao on WordPress + AI & WordCamp Rajasthan! 🚀",type:"video"},
  {id:"SfuJB7OoVmA",title:"WordCamp Mein Contribution Day Kya Hai?",type:"short"},
  {id:"VhXWCeYFkjA",title:"WordCamp Rajasthan 2026 Kya Hai? Jaipur Tech Event",type:"short"},
  {id:"HodvZnduqrY",title:"WordPress Multisites & Epic Roadtrips! 🚗⛺ WordCamp Rajasthan Speaker Interview | WPSimplified",type:"video"},
  {id:"cXZsjbt-64Q",title:"Meet Anand Upadhyay WordCamp's Visionary #wcrajasthan #pinkcity #jaipur",type:"short"},
  {id:"q5K0i3vb-uM",title:"Surat to Jaipur Roadtrip for WordCamp Rajasthan! 🚗⛺ | Volunteering & WordPress + AI",type:"video"},
  {id:"Z6fwtCUz4G0",title:"The Role of Speakers at WordCamp Events #wcrajasthan #pinkcity #jaipur",type:"short"}
];
// AUTO-GENERATED:EXPLORE_VIDEOS_FALLBACK END

// Fallback, used until (or unless) the backend's /offers endpoint responds.
// Admin-managed from /backend/admin/offers — not auto-generated, unlike the
// blocks above, since offers are CampBuddy's own curated list, not sourced
// from the WordCamp event API.
const OFFERS_FALLBACK = [
  {id:1, title:"WordPress.com", description:"Host your site with the creators of WordPress", url:"https://automattic.pxf.io/gOzQ4B", icon:"🌐"},
  {id:2, title:"Pressable", description:"High-performance WordPress hosting", url:"https://automattic.pxf.io/gOzQ4B", icon:"⚡"},
  {id:3, title:"WooCommerce", description:"Build your online store with ease", url:"https://automattic.pxf.io/gOzQ4B", icon:"🛒"},
  {id:4, title:"Jetpack", description:"Essential tools for WordPress sites", url:"https://automattic.pxf.io/gOzQ4B", icon:"🚀"},
  {id:5, title:"Hostinger", description:"Affordable, reliable web hosting", url:"https://www.hostinger.com/in?REFERRALCODE=1RJCODEX35", icon:"🖥"}
];

// --- Live data (CampBuddy backend) --------------------------------------
// Served same-origin by the Slim backend at /backend/api/v1/*, which
// fetches from the upstream WPSimplified API server-side on a schedule and
// caches it — the client never talks to wpsimplified.in directly anymore.
// Response shapes are unchanged (the backend mirrors the upstream shapes
// verbatim), so nothing below this needs to know that moved:
//   /media  -> {items:[{id,title,thumbnail,youtube_link,type}], total, ...}
//   /events -> {events:[{title, event_start_date, event_sponsors:[...], event_agenda:[...], ...}]}
// Everything below still falls back to the static data above if the
// network is unavailable (offline, localhost during dev, etc).
const API_BASE = "/backend/api/v1";
const MEDIA_ENDPOINT = `${API_BASE}/media`;
const EVENTS_ENDPOINT = `${API_BASE}/event`;
const OFFERS_ENDPOINT = `${API_BASE}/offers`;
const CACHE_TTL = 6*3600000;

function cacheGet(key){
  try{
    const raw=localStorage.getItem(key);
    if(!raw) return null;
    const {t,data}=JSON.parse(raw);
    if(Date.now()-t>CACHE_TTL) return null;
    return data;
  }catch(e){return null}
}
function cacheSet(key,data){
  try{localStorage.setItem(key,JSON.stringify({t:Date.now(),data}))}catch(e){}
}
async function fetchJSON(url){
  const controller=new AbortController();
  const timer=setTimeout(()=>controller.abort(),8000);
  try{
    const res=await fetch(url,{signal:controller.signal});
    if(!res.ok) return null;
    return await res.json();
  }catch(e){
    return null;
  }finally{
    clearTimeout(timer);
  }
}

function youtubeIdFromLink(link){
  const m=String(link||"").match(/(?:shorts\/|[?&]v=|youtu\.be\/)([a-zA-Z0-9_-]{6,})/);
  return m?m[1]:null;
}
function normalizeVideos(json){
  const items=json&&Array.isArray(json.items)?json.items:null;
  if(!items) return null;
  const out=items.map(it=>{
    const id=youtubeIdFromLink(it.youtube_link);
    if(!id||!it.title) return null;
    return {id,title:String(it.title),type:it.type==="short"?"short":"video",url:it.youtube_link,thumb:it.thumbnail||null};
  }).filter(Boolean);
  return out.length?out.slice(0,10):null;
}

let exploreVideos=cacheGet("campbuddy-media-v1");
let exploreLoading=false;
async function loadExploreVideos(){
  if(exploreVideos||exploreLoading) return;
  exploreLoading=true;
  const normalized=normalizeVideos(await fetchJSON(MEDIA_ENDPOINT));
  exploreLoading=false;
  if(normalized){
    exploreVideos=normalized;
    cacheSet("campbuddy-media-v1",normalized);
    if(currentRoute()==="explore") render();
  }
}

function normalizeOffers(json){
  const items=json&&Array.isArray(json.offers)?json.offers:null;
  if(!items) return null;
  const out=items.map(o=>{
    if(!o||!o.title||!o.url) return null;
    return {id:o.id,title:String(o.title),description:String(o.description||""),url:o.url,icon:o.icon||"🏷"};
  }).filter(Boolean);
  return out.length?out:null;
}
let liveOffers=cacheGet("campbuddy-offers-v1");
let offersLoading=false;
async function loadOffers(){
  if(liveOffers||offersLoading) return;
  offersLoading=true;
  const normalized=normalizeOffers(await fetchJSON(OFFERS_ENDPOINT));
  offersLoading=false;
  if(normalized){
    liveOffers=normalized;
    cacheSet("campbuddy-offers-v1",normalized);
    if(currentRoute()==="offer") render();
  }
}

// Rajasthan-fort tier names (their API) -> the app's platinum/silver/bronze
// tiers (matches the organizer site's own "Nahargarh Fort / Hawa Mahal /
// Jal Mahal" sponsor-tier naming).
const SPONSOR_TIER_MAP={"Nahargarh Fort":{label:"Platinum",cls:"platinum"},"Hawa Mahal":{label:"Silver",cls:"silver"},"Jal Mahal":{label:"Bronze",cls:"bronze"}};
function sponsorsFromLive(ev){
  if(!Array.isArray(ev.event_sponsors)||!ev.event_sponsors.length) return null;
  const groups={};
  ev.event_sponsors.forEach(s=>{
    if(!s.name) return;
    const tier=SPONSOR_TIER_MAP[s.tier]||{label:s.tier||"Sponsors",cls:"bronze"};
    (groups[tier.label]=groups[tier.label]||{tier:tier.label,cls:tier.cls,items:[]}).items.push({name:s.name,url:s.url||"",logo:s.logo||null});
  });
  const order=["Platinum","Silver","Bronze"];
  const out=order.map(t=>groups[t]).filter(Boolean);
  Object.keys(groups).forEach(t=>{if(!order.includes(t))out.push(groups[t])});
  return out.length?out:null;
}
function agendaFromLive(ev){
  if(!Array.isArray(ev.event_agenda)||!ev.event_agenda.length) return null;
  return ev.event_agenda.map(a=>({day:a.day||"",time:a.time||"",title:a.title||"",desc:a.description||""}));
}
function buildEventPatch(ev){
  const patch={};
  if(ev.title) patch.name=ev.title;
  if(ev.event_tagline) patch.tagline=ev.event_tagline;
  if(ev.event_start_date) patch.starts=`${ev.event_start_date}T09:00:00+05:30`;
  if(ev.event_end_date) patch.conference=`${ev.event_end_date}T09:00:00+05:30`;
  if(ev.event_venue_name) patch.venue=ev.event_venue_name;
  if(ev.event_venue_address) patch.address=ev.event_venue_address;
  if(ev.event_hashtag) patch.hashtag=ev.event_hashtag;
  if(ev.event_home_url) patch.officialUrl=ev.event_home_url;
  if(ev.event_tickets_url) patch.ticketUrl=ev.event_tickets_url;
  if(ev.event_venue_directions_url) patch.directionsUrl=ev.event_venue_directions_url;
  if(ev.event_email) patch.contactUrl=`mailto:${ev.event_email}`;
  if(Array.isArray(ev.event_social)&&ev.event_social.length){
    const socials=ev.event_social.filter(s=>s.label&&s.url).map(s=>[s.label,s.url]);
    if(socials.length) patch.socials=socials;
  }
  if(Array.isArray(ev.event_ticket_types)){
    const general=ev.event_ticket_types.find(t=>/^general ticket$/i.test(t.name||"")&&t.status==="available");
    if(general&&general.price) patch.ticketPrice=`${general.price} for both days`;
  }
  return patch;
}

let liveSponsors=cacheGet("campbuddy-sponsors-v1");
let liveAgenda=cacheGet("campbuddy-agenda-v1");
async function loadEventInfo(){
  const json=await fetchJSON(EVENTS_ENDPOINT);
  const ev=json&&Array.isArray(json.events)?json.events[0]:null;
  if(!ev||typeof ev!=="object") return;
  Object.assign(EVENT,buildEventPatch(ev));
  cacheSet("campbuddy-event-v1",EVENT);
  const sponsors=sponsorsFromLive(ev);
  if(sponsors){liveSponsors=sponsors;cacheSet("campbuddy-sponsors-v1",sponsors);}
  const agenda=agendaFromLive(ev);
  if(agenda){liveAgenda=agenda;cacheSet("campbuddy-agenda-v1",agenda);}
  render();
}
Object.assign(EVENT,cacheGet("campbuddy-event-v1")||{});

const DEMO_SCHEDULE = [
  {id:"arrival",time:"09:00",title:"Arrive, register & find your bearings",track:"CampBuddy suggestion",kind:"helper"},
  {id:"hallway",time:"10:00",title:"Make your first hallway connection",track:"Networking mission",kind:"helper"},
  {id:"lunch",time:"11:30–13:30",title:"Lunch window",track:"Convention Hall",kind:"official"},
  {id:"sponsor",time:"14:00",title:"Explore the Sponsor Hall",track:"Open throughout Conference Day",kind:"official"},
  {id:"reset",time:"16:00",title:"Take a 15-minute recharge break",track:"CampBuddy suggestion",kind:"helper"}
];

const INTERESTS = [
  ["learn","Learn WordPress"],["people","Meet people"],["clients","Find clients"],
  ["job","Career opportunities"],["hire","Hire people"],["contribute","Contribute"],
  ["ai","AI + WordPress"],["business","Agency / business"],["code","Development"],["curious","Just curious 😄"]
];

const CHECKLIST = [
  "Save venue directions",
  "Confirm your WordCamp ticket",
  "Register for Contributor Day if attending",
  "Create / check your WordPress.org account",
  "Join Make WordPress Slack",
  "Pack laptop + charger",
  "Add your details to Camp Card",
  "Pick a few sessions you don't want to miss",
  "Prepare a 15-second introduction"
];

const QUESTS = [
  {id:"hello",icon:"👋",title:"First Hello",text:"Introduce yourself to someone you haven't met before."},
  {id:"city",icon:"🗺️",title:"Beyond My City",text:"Meet someone attending from another city."},
  {id:"speaker",icon:"🎤",title:"Speaker Hello",text:"Say hello to a speaker and thank them for sharing."},
  {id:"contributor",icon:"⌘",title:"Contributor Curious",text:"Meet someone who contributes to WordPress and ask what team they enjoy."},
  {id:"sponsor",icon:"🏢",title:"Sponsor Explorer",text:"Visit a sponsor you haven't heard of and ask what they build."},
  {id:"question",icon:"❓",title:"Asked Something",text:"Ask one useful question — in a session or hallway conversation."},
  {id:"followup",icon:"🔗",title:"Keep the Connection",text:"Exchange contact details with one person you'd genuinely like to stay in touch with."}
];

const MISSIONS = {
  5:["Say hello to the person nearest you and ask what brought them to WordCamp.","Refill your water and introduce yourself to one person on the way back.","Open your Camp Card and make sure your introduction still feels like you."],
  10:["Ask someone: “What are you working on lately?”","Visit one sponsor booth and ask for a 30-second explanation of their product.","Find a first-time attendee and compare what surprised you about WordCamp."],
  15:["Walk into the Sponsor Hall and discover one company you didn't know before.","Find an organizer or volunteer and thank them — then ask what they enjoy about the community.","Sit somewhere new and start one conversation before the next session."],
  20:["Find someone working in a different WordPress role and compare how you use WordPress.","Visit a Contributor table and ask how newcomers can get involved.","Take a proper break: water, food, a short walk, then come back refreshed."]
};

const CONTRIB = [
  {id:"core",name:"Core / Development",emoji:"💻",matches:["code"],desc:"Work on WordPress itself: code, bugs, testing and development workflows."},
  {id:"test",name:"Test",emoji:"🧪",matches:["code","curious"],desc:"Try features, reproduce bugs and improve quality. Great if you enjoy breaking things constructively."},
  {id:"docs",name:"Documentation",emoji:"📚",matches:["learn","curious"],desc:"Improve guides and docs so WordPress is easier for everyone to understand."},
  {id:"polyglots",name:"Polyglots",emoji:"🌍",matches:["people","curious"],desc:"Help translate WordPress and make it accessible in more languages."},
  {id:"community",name:"Community",emoji:"🤝",matches:["people","business","contribute"],desc:"Help make meetups, WordCamps and contributor spaces welcoming and sustainable."},
  {id:"training",name:"Training",emoji:"🎓",matches:["learn","people"],desc:"Create learning material, workshops and educational resources."},
  {id:"design",name:"Design",emoji:"✦",matches:["curious"],desc:"Contribute to user experience, interfaces and design thinking across WordPress."}
];

const SKEY = "campbuddy-rajasthan-v1";
let state = loadState();
let deferredInstall = null;

function defaultState(){
  return {onboarded:false,name:"",interests:[],check:{},quests:{},saved:[],card:{name:"",role:"",ask:"",meet:"",link:""},contribAnswers:[]};
}
function loadState(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(SKEY)||"{}")}}catch(e){return defaultState()}}
function save(){localStorage.setItem(SKEY,JSON.stringify(state))}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function toast(msg){const t=document.createElement("div");t.className="toast";t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),1900)}
function route(name){location.hash=name==="home"?"":name}
function currentRoute(){return location.hash.replace("#","")||"home"}

// --- Analytics (GA4) ----------------------------------------------------
// Never pass Camp Card field values (name/role/ask/meet/link) here — those
// are user-typed personal info and stay local-only, matching the app's own
// privacy promise (and Google Analytics' own terms, which prohibit PII).
function track(name,params){
  if(typeof gtag==="function") gtag("event",name,params||{});
}
let lastTrackedRoute=null;
function trackPageViewIfChanged(){
  const r=currentRoute();
  if(r===lastTrackedRoute) return;
  lastTrackedRoute=r;
  track("page_view",{page_path:`/#${r==="home"?"":r}`,page_title:`CampBuddy · ${r}`,page_location:location.href});
}
// Delegated click tracking for outbound/external links, so every sponsor,
// social, video, useful-link, ticket and organizer-site link is captured
// without hand-wiring each one.
document.addEventListener("click",e=>{
  const a=e.target.closest("a");
  if(!a||!a.href) return;
  const cls=a.className||"";
  const base={link_url:a.href};
  if(cls.includes("video-card")) track("video_click",{...base,video_title:a.querySelector(".video-card__title")?.textContent||""});
  else if(cls.includes("sponsor-chip")) track("sponsor_click",{...base,sponsor_name:(a.querySelector("img")?.alt||a.textContent||"").trim()});
  else if(cls.includes("social-chip")) track("social_click",{...base,platform:a.textContent.trim()});
  else if(cls.includes("ticket-banner__cta")) track("ticket_click",base);
  else if(cls.includes("useful-link")) track("useful_link_click",{...base,link_label:a.querySelector(".useful-link__title")?.textContent||""});
  else if(cls.includes("offer-card")) track("offer_click",{...base,offer_title:a.querySelector(".offer-card__title")?.textContent||""});
  else if(a.target==="_blank") track("outbound_click",base);
});

function render(){
  trackPageViewIfChanged();
  const r=currentRoute();
  document.querySelectorAll(".bottom-nav__item").forEach(x=>x.classList.toggle("bottom-nav__item--active",x.dataset.route===r));
  const app=document.getElementById("app");
  app.innerHTML = ({home:homeView,schedule:scheduleView,"official-schedule":officialScheduleView,quests:questsView,contribute:contributeView,explore:exploreView,offer:offerView,card:cardView,more:moreView}[r]||homeView)();
  app.focus({preventScroll:true});
  bindDynamic();
}

function homeView(){
  const who = state.name ? `, ${esc(state.name.split(" ")[0])}` : "";
  const done = CHECKLIST.filter((_,i)=>state.check[i]).length;
  const questDone = QUESTS.filter(q=>state.quests[q.id]).length;
  return `
    <section class="hero">
      <div class="hero__khamma">खम्मा घणी · PADHARO MHARE DESH</div>
      <h1 class="hero__title">Your WordCamp${who}. Minus the awkward bits.</h1>
      <p class="hero__text">A tiny first-timer companion for knowing what to do, where to go and who to meet.</p>
      <div class="hero__meta">${EVENT.facts.map(x=>`<span class="pill">${x}</span>`).join("")}<span class="pill pill--hashtag">${EVENT.hashtag}</span></div>
    </section>

    <section class="u-section">
      <div class="section-head"><div><div class="u-eyebrow">COUNTDOWN</div><h2 class="section-head__title">See you in Jaipur</h2></div></div>
      <div class="card">${countdownMarkup()}<p class="u-muted" style="margin-bottom:0">Rajasthan International Centre · Jhalana Doongri, Jaipur</p>
        <div class="ticket-banner"><div><strong class="ticket-banner__title">Haven't booked yet?</strong><small class="ticket-banner__price">${EVENT.ticketPrice}</small></div><a class="ticket-banner__cta" href="${EVENT.ticketUrl}" target="_blank" rel="noopener">Get ticket ↗</a></div>
      </div>
    </section>

    <section class="u-section">
      <div class="section-head"><div><div class="u-eyebrow">RIGHT NOW</div><h2 class="section-head__title">${rightNowHeading()}</h2></div></div>
      <div class="card card--now">${rightNowBody()}</div>
    </section>

    <section class="u-section">
      <div class="section-head"><div><div class="u-eyebrow">QUICK START</div><h2 class="section-head__title">What do you need?</h2></div></div>
      <div class="action-grid">
        ${action("⏱","I have free time","Get a tiny social mission","free-time")}
        ${action("✓",`Camp Quest · ${questDone}/${QUESTS.length}`,"Make meeting people easier","quests")}
        ${action("⌘","Where can I contribute?","Find a friendly Contributor team","contribute")}
        ${action("▶","Explore","WordCamp Rajasthan on YouTube","explore")}
        ${action("▣","My Camp Card","A simple intro you can show people","card",true)}
      </div>
    </section>

    <section class="u-section">
      <div class="section-head"><div><div class="u-eyebrow">BEFORE YOU GO</div><h2 class="section-head__title">${done}/${CHECKLIST.length} ready</h2></div><span class="badge">${Math.round(done/CHECKLIST.length*100)}%</span></div>
      <div class="progress"><span class="progress__bar" style="width:${done/CHECKLIST.length*100}%"></span></div>
      <div class="checklist" style="margin-top:12px">
        ${CHECKLIST.map((x,i)=>`<label class="checklist__item ${state.check[i]?"checklist__item--done":""}"><input class="checklist__input" type="checkbox" data-check="${i}" ${state.check[i]?"checked":""}><span class="checklist__label">${esc(x)}</span></label>`).join("")}
      </div>
    </section>

    <section class="u-section">
      <div class="card">
        <div class="u-row u-between"><div><div class="u-eyebrow">USEFUL STUFF</div><h2 style="margin:5px 0">The links you'll actually need</h2></div><button class="btn btn--ghost btn--compact" data-route="more">Open</button></div>
      </div>
    </section>
    ${footer()}
  `;
}

function countdownMarkup(){
  const target=new Date(EVENT.starts).getTime(), now=Date.now(), diff=Math.max(0,target-now);
  const d=Math.floor(diff/86400000),h=Math.floor(diff/3600000)%24,m=Math.floor(diff/60000)%60,s=Math.floor(diff/1000)%60;
  return `<div class="countdown"><div class="countdown__box"><b class="countdown__value">${d}</b><small class="countdown__label">days</small></div><div class="countdown__box"><b class="countdown__value">${h}</b><small class="countdown__label">hours</small></div><div class="countdown__box"><b class="countdown__value">${m}</b><small class="countdown__label">mins</small></div><div class="countdown__box"><b class="countdown__value">${s}</b><small class="countdown__label">secs</small></div></div>`;
}
function rightNowHeading(){
  const now=Date.now(), start=new Date(EVENT.starts).getTime(), conf=new Date(EVENT.conference).getTime(), end=conf+12*3600000;
  if(now<start) return "Get ready without overthinking it";
  if(now<conf) return "Contributor Day";
  if(now<end) return "Conference Day";
  return "Keep the connections going";
}
function rightNowBody(){
  const now=Date.now(), start=new Date(EVENT.starts).getTime(), conf=new Date(EVENT.conference).getTime(), end=conf+12*3600000;
  if(now<start) return `<div class="u-row"><div class="u-dot"></div><div class="u-grow"><strong>Do one small thing today</strong><p class="u-muted">Finish a checklist item, create your Camp Card, or find your Contributor team.</p></div></div><button class="btn btn--primary btn--full" data-route="card">Create my Camp Card</button>`;
  if(now<conf) return `<strong>New to Contributor Day?</strong><p class="u-muted">Walk up to a table and say: “Hi, this is my first Contributor Day. Can you help me get started?” That's enough.</p><button class="btn btn--primary btn--full" data-route="contribute">Find a team</button>`;
  if(now<end) return `<strong>Conference mode: learn + meet people.</strong><p class="u-muted">The Sponsor Hall is open throughout the day. Lunch is listed by the organizers for 11:30 AM–1:30 PM in Convention Hall.</p><button class="btn btn--primary btn--full" data-free-time="10">Give me a 10-minute mission</button>`;
  return `<strong>Don't let the good conversations disappear.</strong><p class="u-muted">Connect with the people you met, send the link you promised, and pick one way to stay involved with WordPress.</p>`;
}
function action(icon,title,desc,target,wide){
  const attr=target==="free-time" ? `data-free-time="10"` : `data-route="${target}"`;
  return `<button class="action-card${wide?" action-card--wide":""}" ${attr}><span class="action-card__icon">${icon}</span><span><strong class="action-card__title">${title}</strong><small class="action-card__desc">${desc}</small></span></button>`;
}

function scheduleView(){
  const saved=state.saved;
  return `
  <section class="u-page-intro">
    <div class="u-eyebrow">MY DAY</div><h1 style="margin:6px 0 8px">A calmer conference plan</h1>
    <p class="u-muted">This prototype intentionally does not invent unverified session times. Official Rajasthan schedule data can be dropped into the event data layer later.</p>
    <div class="notice">Verified organizer info included here: Conference Day is 4 October, two parallel tracks, Sponsor Hall open throughout the day, and lunch is listed for 11:30 AM–1:30 PM in Convention Hall.</div>
  </section>
  <section class="u-section">
    <div class="section-head"><div><div class="u-eyebrow">STARTER PLAN</div><h2 class="section-head__title">Helpful anchors</h2></div></div>
    <div class="card">
      ${DEMO_SCHEDULE.map(s=>`<div class="schedule-item"><div class="schedule-item__time">${s.time}</div><div><strong>${esc(s.title)}</strong><span class="schedule-item__track">${esc(s.track)} · ${s.kind==="official"?"verified":"suggestion"}</span></div><button class="schedule-item__star ${saved.includes(s.id)?"schedule-item__star--saved":""}" data-save="${s.id}" aria-label="Save">${saved.includes(s.id)?"★":"☆"}</button></div>`).join("")}
    </div>
  </section>
  <section class="u-section"><button class="btn btn--primary btn--full" data-route="official-schedule">Open official schedule ↗</button></section>
  ${footer()}`;
}

// Day 01 (Contributor Day) sessions live in the Contribute tab instead —
// see contributeView(). This is the rest of the live agenda (Sunday, etc).
function isContributorDay(day){return /^Day\s*01\b/i.test(day||"")}
function officialScheduleView(){
  const saved=state.saved;
  if(!liveAgenda){
    return `
    <section class="u-page-intro"><div class="u-eyebrow">OFFICIAL SCHEDULE</div><h1 style="margin:6px 0 8px">Not available offline</h1><p class="u-muted">The live schedule couldn't be loaded. Try again once you're back online, or use the organizer's site directly.</p></section>
    <section class="u-section"><a class="btn btn--primary btn--full" href="${EVENT.scheduleUrl}" target="_blank" rel="noopener">Open on the organizer site ↗</a></section>
    ${footer()}`;
  }
  const days=[...new Set(liveAgenda.filter(a=>!isContributorDay(a.day)).map(a=>a.day))];
  return `
  <section class="u-page-intro">
    <div class="u-eyebrow">OFFICIAL SCHEDULE</div><h1 style="margin:6px 0 8px">Straight from the organizers</h1>
    <p class="u-muted">Pulled live from the published agenda. Tap a star to save a session to come back to. Looking for Contributor Day? That's on the Contribute tab.</p>
  </section>
  ${days.map(day=>`
  <section class="u-section">
    <div class="section-head"><div><div class="u-eyebrow">${esc(day)}</div><h2 class="section-head__title">Sessions</h2></div></div>
    <div class="card">
      ${liveAgenda.filter(a=>a.day===day).map((s,i)=>{
        const id=`agenda-${slug(day)}-${i}`;
        return `<div class="schedule-item"><div class="schedule-item__time">${esc(s.time)}</div><div><strong>${esc(s.title)}</strong>${s.desc?`<span class="schedule-item__track">${esc(s.desc)}</span>`:""}</div><button class="schedule-item__star ${saved.includes(id)?"schedule-item__star--saved":""}" data-save="${id}" aria-label="Save">${saved.includes(id)?"★":"☆"}</button></div>`;
      }).join("")}
    </div>
  </section>`).join("")}
  <section class="u-section"><a class="btn btn--ghost btn--full" href="${EVENT.scheduleUrl}" target="_blank" rel="noopener">Open on the organizer site ↗</a></section>
  ${footer()}`;
}

function questsView(){
  const done=QUESTS.filter(q=>state.quests[q.id]).length;
  return `
  <section class="u-page-intro"><div class="u-eyebrow">CAMP QUEST</div><h1 style="margin:6px 0">Make the room feel smaller.</h1><p class="u-muted">No leaderboard. No points economy. Just a few nudges that make meeting people less weird.</p></section>
  <section class="u-section"><div class="u-row u-between"><strong>${done}/${QUESTS.length} complete</strong><span class="badge">${done===QUESTS.length?"Legend ✨":"Your pace"}</span></div><div class="progress" style="margin-top:10px"><span class="progress__bar" style="width:${done/QUESTS.length*100}%"></span></div></section>
  <section class="u-section">
    ${QUESTS.map(q=>`<div class="card quest ${state.quests[q.id]?"quest--done":""}"><div class="quest__top"><div><div class="quest__icon">${q.icon}</div><h3 style="margin:8px 0 4px">${q.title}</h3><p class="u-muted" style="margin:0">${q.text}</p></div>${state.quests[q.id]?'<span class="badge">Done</span>':''}</div><button class="btn ${state.quests[q.id]?"btn--ghost":"btn--primary"}" data-quest="${q.id}">${state.quests[q.id]?"Undo":"I did this ✓"}</button></div>`).join("")}
  </section>
  ${footer()}`;
}

function contributeView(){
  const matches=contribMatches();
  const day1=liveAgenda?liveAgenda.filter(a=>isContributorDay(a.day)):null;
  return `
  <section class="u-page-intro"><div class="u-eyebrow">CONTRIBUTOR DAY</div><h1 style="margin:6px 0">Where could I help?</h1><p class="u-muted">Contributor Day is for developers, designers, writers, translators, testers, educators and curious newcomers — not only coders.</p></section>
  ${day1&&day1.length?`
  <section class="u-section">
    <div class="section-head"><div><div class="u-eyebrow">${esc(day1[0].day)}</div><h2 class="section-head__title">Day 01 schedule</h2></div></div>
    <div class="card">
      ${day1.map((s,i)=>{
        const id=`agenda-${slug(day1[0].day)}-${i}`;
        return `<div class="schedule-item"><div class="schedule-item__time">${esc(s.time)}</div><div><strong>${esc(s.title)}</strong>${s.desc?`<span class="schedule-item__track">${esc(s.desc)}</span>`:""}</div><button class="schedule-item__star ${state.saved.includes(id)?"schedule-item__star--saved":""}" data-save="${id}" aria-label="Save">${state.saved.includes(id)?"★":"☆"}</button></div>`;
      }).join("")}
    </div>
  </section>`:""}
  <section class="u-section card">
    <h3 style="margin-top:0">What sounds most like you?</h3>
    <div class="chip-group">
      ${[["code","I like code"],["people","I like helping people"],["learn","I like teaching / writing"],["curious","I like testing things"],["contribute","I just want to try"]].map(([id,l])=>`<button class="chip ${state.contribAnswers.includes(id)?"chip--selected":""}" data-contrib="${id}">${l}</button>`).join("")}
    </div>
    <p class="u-muted" style="margin-bottom:0">Pick a few. There isn't a wrong team.</p>
  </section>
  <section class="u-section">
    <div class="section-head"><div><div class="u-eyebrow">GOOD STARTING POINTS</div><h2 class="section-head__title">${matches.length? "Try these tables":"Pick an option above"}</h2></div></div>
    ${matches.map(x=>`<div class="contributor-result"><div class="u-row"><span style="font-size:30px">${x.emoji}</span><div><strong>${x.name}</strong><p class="u-muted" style="margin:4px 0 0">${x.desc}</p></div></div></div>`).join("")}
    ${matches.length?`<div class="card" style="margin-top:12px"><div class="u-eyebrow">YOUR OPENING LINE</div><p class="mission-big" style="font-size:18px">“Hi, this is my first Contributor Day. Can you help me get started?”</p><p class="u-muted" style="margin-bottom:0">Seriously. That's enough.</p></div>`:""}
  </section>
  <section class="u-section"><a href="${EVENT.contributorUrl}" target="_blank" rel="noopener" class="btn btn--ghost btn--full">Official Contributor Day info ↗</a></section>
  ${footer()}`;
}
function contribMatches(){
  if(!state.contribAnswers.length)return [];
  return CONTRIB.map(x=>({...x,score:x.matches.filter(m=>state.contribAnswers.includes(m)).length})).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,4);
}

function exploreView(){
  loadExploreVideos();
  const videos=exploreVideos||EXPLORE_VIDEOS_FALLBACK;
  return `
  <section class="u-page-intro"><div class="u-eyebrow">EXPLORE</div><h1 style="margin:6px 0">WordCamp Rajasthan, in short clips.</h1><p class="u-muted">Hand-picked from WPSimplified — WordPress tutorials and WordCamp Rajasthan updates from an organizer's lens.</p></section>
  <section class="u-section">
    <div class="video-grid">
      ${videos.map(v=>`
        <a class="video-card" href="${videoUrl(v)}" target="_blank" rel="noopener">
          <div class="video-card__thumb"><img src="${v.thumb||`https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`}" alt="" loading="lazy">${v.type==="short"?'<span class="video-card__badge">Shorts</span>':''}</div>
          <div class="video-card__meta"><strong class="video-card__title">${esc(v.title)}</strong>${v.date?`<small class="video-card__date">${relTime(v.date)}</small>`:""}</div>
        </a>`).join("")}
    </div>
  </section>
  <section class="u-section"><a class="btn btn--ghost btn--full" href="${EXPLORE_CHANNEL_URL}" target="_blank" rel="noopener">More on WPSimplified ↗</a></section>
  ${footer()}`;
}
function videoUrl(v){return v.url||(v.type==="short"?`https://www.youtube.com/shorts/${v.id}`:`https://www.youtube.com/watch?v=${v.id}`)}

function offerView(){
  loadOffers();
  const offers=liveOffers||OFFERS_FALLBACK;
  return `
  <section class="u-page-intro"><div class="u-eyebrow">OFFERS</div><h1 style="margin:6px 0">Deals worth a look.</h1><p class="u-muted">Hosting and tools from the WordPress ecosystem — CampBuddy may earn a commission at no extra cost to you.</p></section>
  <section class="u-section">
    <div class="offer-grid">
      ${offers.map(o=>`
        <a class="offer-card" href="${o.url}" target="_blank" rel="noopener sponsored">
          <span class="offer-card__icon">${o.icon}</span>
          <strong class="offer-card__title">${esc(o.title)}</strong>
          <small class="offer-card__desc">${esc(o.description)}</small>
        </a>`).join("")}
    </div>
  </section>
  ${footer()}`;
}
function relTime(iso){
  const days=Math.floor((Date.now()-new Date(iso).getTime())/86400000);
  if(days<=0) return "Today";
  if(days===1) return "1 day ago";
  if(days<30) return `${days} days ago`;
  const months=Math.floor(days/30);
  return months===1?"1 month ago":`${months} months ago`;
}

function cardView(){
  const c={...state.card};
  if(!c.name && state.name)c.name=state.name;
  const ask=(c.ask||"WordPress · what I'm building").split(",").map(x=>x.trim()).filter(Boolean).slice(0,4);
  const meet=(c.meet||"People doing interesting things").split(",").map(x=>x.trim()).filter(Boolean).slice(0,3);
  return `
  <section class="u-page-intro"><div class="u-eyebrow">CAMP CARD</div><h1 style="margin:6px 0">An introduction without the awkward intro.</h1><p class="u-muted">Fill it in, then show the card or QR to someone you meet. Everything stays in your browser.</p></section>
  <section class="u-section">
    <div class="camp-card">
      <div class="camp-card__label">WORDCAMP RAJASTHAN 2026</div>
      <h2 class="camp-card__name">${esc(c.name||"Your name")}</h2>
      <div class="camp-card__role">${esc(c.role||"What you do / what you're learning")}</div>
      <div class="camp-card__label">ASK ME ABOUT</div><div class="camp-card__tags">${ask.map(x=>`<span class="camp-card__tag">${esc(x)}</span>`).join("")}</div>
      <div class="camp-card__label">I'D LOVE TO MEET</div><div class="camp-card__tags">${meet.map(x=>`<span class="camp-card__tag">${esc(x)}</span>`).join("")}</div>
    </div>
  </section>
  <section class="u-section card">
    <label class="field"><span>Name</span><input data-card="name" value="${esc(c.name)}" placeholder="Your name"></label>
    <label class="field"><span>What do you do?</span><input data-card="role" value="${esc(c.role)}" placeholder="Developer, designer, student, agency owner…"></label>
    <label class="field"><span>Ask me about <small>comma separated</small></span><input data-card="ask" value="${esc(c.ask)}" placeholder="Multisite, WooCommerce, design"></label>
    <label class="field"><span>I'd love to meet <small>comma separated</small></span><input data-card="meet" value="${esc(c.meet)}" placeholder="Contributors, agency owners, developers"></label>
    <label class="field"><span>One link</span><input data-card="link" value="${esc(c.link)}" placeholder="https://linkedin.com/in/..."></label>
    <button class="btn btn--primary btn--full" id="showQR">Show share QR</button>
    <div id="qrArea"></div>
  </section>
  ${footer()}`;
}

function moreView(){
  return `
  <section class="u-page-intro"><div class="u-eyebrow">USEFUL STUFF</div><h1 style="margin:6px 0">Keep the boring things easy.</h1></section>
  <section class="u-section card">
    ${useful("🎟️","Get your ticket",EVENT.ticketPrice,EVENT.ticketUrl)}
    ${useful("📍","Venue directions",`${EVENT.venue}, ${EVENT.address}`,EVENT.directionsUrl)}
    ${useful("🗓️","Official schedule","Always use the organizer page for last-minute changes",EVENT.scheduleUrl)}
    ${useful("⌘","Contributor Day","Official registration and preparation details",EVENT.contributorUrl)}
    ${useful("🌐","WordCamp Rajasthan","Event homepage",EVENT.officialUrl)}
    ${useful("🤝","Code of Conduct","What to expect from this community",EVENT.codeOfConductUrl)}
    ${useful("✉️","Contact organizers","Questions about tickets, venue or accessibility",EVENT.contactUrl)}
  </section>
  <section class="u-section card">
    <div class="u-eyebrow">SPONSORS</div><h2 class="u-card-title">Made possible by</h2>
    ${(liveSponsors||SPONSORS_FALLBACK).map(t=>`<div class="sponsor-group"><div class="u-eyebrow">${t.tier.toUpperCase()}</div><div class="sponsor-group__row">${t.items.map(s=>`<a class="sponsor-chip sponsor-chip--${t.cls}" href="${s.url||EVENT.sponsorsUrl}" target="_blank" rel="noopener">${s.logo?`<img class="sponsor-chip__logo" src="${s.logo}" alt="${esc(s.name)}">`:esc(s.name)}</a>`).join("")}</div></div>`).join("")}
    <a href="${EVENT.sponsorsUrl}" target="_blank" rel="noopener" class="btn btn--ghost btn--full" style="margin-top:14px">All sponsors ↗</a>
  </section>
  <section class="u-section card">
    <div class="u-eyebrow">STAY IN THE LOOP</div><h2 class="u-card-title">Follow along</h2>
    <div class="social-list">${EVENT.socials.map(([n,u])=>`<a class="social-chip" href="${u}" target="_blank" rel="noopener">${esc(n)}</a>`).join("")}</div>
    <p class="u-muted" style="margin:10px 0 0">Share using <strong>${EVENT.hashtag}</strong></p>
  </section>
  <section class="u-section card about">
    <img class="about__logo" src="./wcr/web/logo-header.png" alt="WordCamp Rajasthan 2026">
    <div class="u-eyebrow">ABOUT &amp; PRIVACY</div><h2 class="u-card-title">What CampBuddy is (and isn't)</h2>
    <p class="u-muted">CampBuddy is a lightweight, mobile-first companion designed to make WordCamps easier and more welcoming, especially for first-time attendees.</p>
    <p class="u-muted">The app helps attendees understand what to do before and during the event, discover Contributor Day opportunities, plan their day, meet new people through simple networking prompts, and create a small personal Camp Card for easier introductions.</p>
    <p class="u-muted">The goal is not to replace the official WordCamp website or schedule. Instead, CampBuddy acts as a friendly layer on top of the event information, helping attendees navigate the experience with less confusion and more confidence.</p>
    <p class="u-muted" style="margin-bottom:0">It is intentionally simple, privacy-friendly, and accessible without requiring an account. Most attendee preferences and progress are stored directly on their device, making the app inexpensive to host and easy for different WordCamps to adopt in the future.</p>
  </section>
  <section class="u-section card">
    <div class="u-eyebrow">YOUR DATA</div><h2 class="u-card-title">Local by default</h2><p class="u-muted">Your checklist, quests and Camp Card are stored only in this browser. No CampBuddy account is required.</p>
    <p class="u-muted">CampBuddy uses Google Analytics to see anonymous, aggregate usage — things like which tabs get used and whether the QR feature helps. It never sees the words you type into your Camp Card (your name, role, or links) or anything else you enter; those stay on your device unless you tap Export.</p>
    <button class="btn btn--ghost btn--full" id="exportData">Export my CampBuddy data</button>
    <button class="btn btn--danger btn--full" id="resetData">Reset everything</button>
  </section>
  ${footer()}`;
}
function useful(icon,title,desc,url){return `<a class="useful-link" href="${url}" target="_blank" rel="noopener"><span class="useful-link__icon">${icon}</span><span class="u-grow"><b class="useful-link__title">${title}</b><small class="useful-link__desc">${desc}</small></span><span class="useful-link__arrow">↗</span></a>`}
function footer(){return `<div class="footer-note">CampBuddy · open-source first-timer companion<br>Built for the WordPress community · local-first & no login</div>`}

function bindDynamic(){
  document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>route(b.dataset.route));
  document.querySelectorAll("[data-check]").forEach(x=>x.onchange=()=>{state.check[x.dataset.check]=x.checked;save();track("checklist_toggle",{item_index:x.dataset.check,checked:x.checked});render();if(CHECKLIST.every((_,i)=>state.check[i]))track("checklist_complete",{});});
  document.querySelectorAll("[data-quest]").forEach(b=>b.onclick=()=>{state.quests[b.dataset.quest]=!state.quests[b.dataset.quest];save();track("quest_toggle",{quest_id:b.dataset.quest,done:!!state.quests[b.dataset.quest]});render();if(QUESTS.every(q=>state.quests[q.id]))track("quest_all_complete",{});});
  document.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>{const id=b.dataset.save;const nowSaved=!state.saved.includes(id);state.saved=nowSaved?[...state.saved,id]:state.saved.filter(x=>x!==id);save();track("schedule_save_toggle",{session_id:id,saved:nowSaved});render()});
  document.querySelectorAll("[data-free-time]").forEach(b=>b.onclick=()=>openMission(Number(b.dataset.freeTime)||10));
  document.querySelectorAll("[data-contrib]").forEach(b=>b.onclick=()=>{const id=b.dataset.contrib;const nowSelected=!state.contribAnswers.includes(id);state.contribAnswers=nowSelected?[...state.contribAnswers,id]:state.contribAnswers.filter(x=>x!==id);save();track("contrib_interest_toggle",{tag:id,selected:nowSelected});render()});
  document.querySelectorAll("[data-card]").forEach(i=>i.oninput=()=>{state.card[i.dataset.card]=i.value;if(i.dataset.card==="name")state.name=i.value;save();});
  const qr=document.getElementById("showQR"); if(qr) qr.onclick=()=>{track("camp_card_qr_view",{});renderQR()};
  const exp=document.getElementById("exportData"); if(exp) exp.onclick=()=>{track("data_export",{});exportData()};
  const reset=document.getElementById("resetData"); if(reset) reset.onclick=()=>{if(confirm("Reset CampBuddy on this device?")){track("data_reset",{});localStorage.removeItem(SKEY);state=defaultState();render();showOnboarding()}};
}

function openMission(minutes=10){
  const list=MISSIONS[minutes]||MISSIONS[10], mission=list[Math.floor(Math.random()*list.length)];
  track("free_time_mission_view",{minutes});
  document.getElementById("freeTimeTitle").textContent=`You have ${minutes} minutes`;
  document.getElementById("freeTimeMission").textContent=mission;
  document.getElementById("freeTimeDialog").showModal();
}
document.getElementById("anotherMission").onclick=()=>openMission(10);

function campPayload(){
  const c=state.card; const parts=[
    c.name||state.name, c.role, c.ask&&`Ask me about: ${c.ask}`, c.meet&&`I'd love to meet: ${c.meet}`, c.link
  ].filter(Boolean);
  return parts.join("\n");
}
async function renderQR(){
  const area=document.getElementById("qrArea");
  const payload=campPayload();
  if(!payload){toast("Add at least your name or one detail first");return}
  area.innerHTML=`<div class="qr__box" id="qrBox"></div>
    <div class="qr__actions"><button class="btn btn--ghost btn--compact" id="qrDownload">⬇ Download</button><button class="btn btn--primary btn--compact" id="qrShare">⇪ Share</button></div>
    <p class="u-muted" style="text-align:center;font-size:12px;margin-top:8px">Generated entirely on your device — nothing is uploaded.</p>`;
  const canvas=await drawBrandedQR(payload);
  document.getElementById("qrBox").appendChild(canvas);
  document.getElementById("qrDownload").onclick=()=>downloadCanvas(canvas,state.card.name||state.name);
  document.getElementById("qrShare").onclick=()=>shareCanvas(canvas,payload);
}
function drawBrandedQR(payload){
  return new Promise(resolve=>{
    const qr=qrcode(0,"H");
    qr.addData(payload);
    qr.make();
    const count=qr.getModuleCount();
    const cell=Math.max(6,Math.round(560/(count+8)));
    const margin=cell*4;
    const size=count*cell+margin*2;
    const canvas=document.createElement("canvas");
    canvas.width=size;canvas.height=size;
    const ctx=canvas.getContext("2d");
    ctx.fillStyle="#fffaf4";ctx.fillRect(0,0,size,size);
    ctx.fillStyle="#0d2343";
    for(let r=0;r<count;r++)for(let c=0;c<count;c++)if(qr.isDark(r,c))ctx.fillRect(margin+c*cell,margin+r*cell,cell,cell);
    const markSize=size*0.2, mx=(size-markSize)/2, my=(size-markSize)/2, pad=cell*1.2;
    ctx.fillStyle="#fffaf4";
    roundRect(ctx,mx-pad,my-pad,markSize+pad*2,markSize+pad*2,14);
    ctx.fill();
    const logo=new Image();
    logo.onload=()=>{ctx.drawImage(logo,mx,my,markSize,markSize);resolve(canvas)};
    logo.onerror=()=>resolve(canvas);
    logo.src="./wcr/web/qr-mark.png";
  });
}
function roundRect(ctx,x,y,w,h,r){
  ctx.beginPath();
  ctx.moveTo(x+r,y);
  ctx.arcTo(x+w,y,x+w,y+h,r);
  ctx.arcTo(x+w,y+h,x,y+h,r);
  ctx.arcTo(x,y+h,x,y,r);
  ctx.arcTo(x,y,x+w,y,r);
  ctx.closePath();
}
function slug(s){return String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")||"me"}
function downloadCanvas(canvas,name){
  // Analytics only ever gets a static, generic file_name — never the
  // person's real name, even though the actual downloaded file (a local
  // save, sent nowhere) is personalized via slug(name) below.
  track("file_download",{file_name:"campbuddy-card.png",file_extension:"png"});
  canvas.toBlob(blob=>{
    const a=document.createElement("a");
    a.href=URL.createObjectURL(blob);
    a.download=`campbuddy-card-${slug(name)}.png`;
    a.click();
    setTimeout(()=>URL.revokeObjectURL(a.href),1000);
  });
}
function shareCanvas(canvas,payload){
  canvas.toBlob(async blob=>{
    const file=new File([blob],"campbuddy-card.png",{type:"image/png"});
    const shareText=`My CampBuddy card for ${EVENT.name}\n\n${payload}`;
    try{
      if(navigator.canShare && navigator.canShare({files:[file]})){
        await navigator.share({files:[file],title:"My CampBuddy Card",text:shareText});
        track("share",{method:"web_share_api",content_type:"camp_card_qr"});
      }else if(navigator.share){
        await navigator.share({title:"My CampBuddy Card",text:shareText});
        track("share",{method:"web_share_api_text_only",content_type:"camp_card_qr"});
      }else{
        downloadCanvas(canvas,state.card.name||state.name);
        track("share",{method:"download_fallback",content_type:"camp_card_qr"});
        toast("Sharing isn't supported here — downloaded instead");
      }
    }catch(e){/* user cancelled the share sheet */}
  });
}
function exportData(){
  const blob=new Blob([JSON.stringify({event:EVENT.id,exportedAt:new Date().toISOString(),data:state},null,2)],{type:"application/json"});
  const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="campbuddy-data.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}

function showOnboarding(){
  if(state.onboarded)return;
  track("tutorial_begin",{});
  const picker=document.getElementById("interestPicker");
  picker.innerHTML=INTERESTS.map(([id,l])=>`<button type="button" class="chip" data-interest="${id}">${l}</button>`).join("");
  picker.querySelectorAll("button").forEach(b=>b.onclick=()=>b.classList.toggle("chip--selected"));
  document.getElementById("onboarding").showModal();
}
document.getElementById("onboardingForm").addEventListener("submit",()=>{
  state.interests=[...document.querySelectorAll("[data-interest].chip--selected")].map(x=>x.dataset.interest);
  state.name=document.getElementById("onboardName").value.trim();
  state.card.name=state.name;
  state.onboarded=true;save();
  // Interest tags are predefined categories (e.g. "learn","people"), not
  // free text — safe to send. The typed name never is.
  track("tutorial_complete",{method:"completed",interests:state.interests.join(","),interests_count:state.interests.length,named:!!state.name});
  render();
});
document.getElementById("skipOnboarding").onclick=()=>{state.onboarded=true;save();track("tutorial_complete",{method:"skipped"});document.getElementById("onboarding").close();render()};

window.addEventListener("hashchange",render);
window.addEventListener("beforeinstallprompt",e=>{
  e.preventDefault();deferredInstall=e;
  track("pwa_install_prompt_shown",{});
  const b=document.getElementById("installBtn");b.hidden=false;
  b.onclick=async()=>{
    deferredInstall.prompt();
    const choice=await deferredInstall.userChoice;
    track("pwa_install_outcome",{outcome:choice.outcome});
    b.hidden=true;deferredInstall=null;
  };
});
document.querySelectorAll(".brand,[data-route]").forEach(b=>b.addEventListener("click",()=>route(b.dataset.route)));

if("serviceWorker" in navigator) window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
render();
setInterval(()=>{if(currentRoute()==="home")render()},1000);
setTimeout(showOnboarding,250);
loadEventInfo();
